### ISSUE TITLE
[0.3.0] 1 test failing

### ISSUE THREAD

**Issue by remicollet** [bwoebi/php-uv#108]
```
TEST 19/53 [tests/200-ares_getaddrinfo.phpt]
========DIFF========
001+ Deprecated: uv_getaddrinfo(): Passing null to parameter #4 ($service) of type string is deprecated in /dev/shm/BUILD/php-pecl-uv-0.3.0/NTS/tests/200-ares_getaddrinfo.php on line 10
002+ 
003+ Deprecated: uv_getaddrinfo(): Passing null to parameter #4 ($service) of type string is deprecated in /dev/shm/BUILD/php-pecl-uv-0.3.0/NTS/tests/200-ares_getaddrinfo.php on line 21
004+ 
001- status: 0
002- OK
003- status: 0
004- OK
005+ Fatal error: Uncaught ArgumentCountError: Too few arguments to function {closure}(), 1 passed and exactly 2 expected in /dev/shm/BUILD/php-pecl-uv-0.3.0/NTS/tests/200-ares_getaddrinfo.php:2
006+ Stack trace:
007+ #0 [internal function]: {closure}(Array)
008+ #1 /dev/shm/BUILD/php-pecl-uv-0.3.0/NTS/tests/200-ares_getaddrinfo.php(24): uv_run()
009+ #2 {main}
010+   thrown in /dev/shm/BUILD/php-pecl-uv-0.3.0/NTS/tests/200-ares_getaddrinfo.php on line 2
========DONE========
FAIL Check for ares_getaddrinfo [tests/200-ares_getaddrinfo.phpt] 

```

**Comment by andypost** [comment]
I need to disable 2 more tests related to building on Alpinelinux additionally to this one

**Comment by kelunik** [comment]
@andypost Could you please include details like @remicollet?

I totally missed this issue somehow, will have a look.

**Comment by andypost** [comment]
@kelunik sure, here's details

PHP 8.3 additionally to `ares_getaddrinfo` fails:
```
TEST 6/53 [tests/005-uv_listen_cb-not-destroyed.phpt]
========DIFF========
     OK
002- OK
003- OK
004- OK
========DONE========
FAIL Check for uv_listen callback is not destroyed by gc [tests/005-uv_listen_cb-not-destroyed.phpt] 
```

and in CI (no tty)
```
TEST 42/53 [tests/800-uv_tty.phpt]
========DIFF========
001- OK
002- OK
001+ Fatal error: Uncaught TypeError: uv_tty_init(): Argument #2 ($fd) must be of type resource, int given in /builds/alpine/aports/testing/php84-pecl-uv/src/uv-0.3.0/tests/800-uv_tty.php:3
002+ Stack trace:
003+ #0 /builds/alpine/aports/testing/php84-pecl-uv/src/uv-0.3.0/tests/800-uv_tty.php(3): uv_tty_init(Object(UVLoop), -6, 1)
004+ #1 [internal function]: {closure:/builds/alpine/aports/testing/php84-pecl-uv/src/uv-0.3.0/tests/800-uv_tty.php:2}(-6)
005+ #2 /builds/alpine/aports/testing/php84-pecl-uv/src/uv-0.3.0/tests/800-uv_tty.php(13): uv_run()
006+ #3 {main}
007+   thrown in /builds/alpine/aports/testing/php84-pecl-uv/src/uv-0.3.0/tests/800-uv_tty.php on line 3
========DONE========
FAIL Check for uv_tty [tests/800-uv_tty.phpt] 
```

moreover on PPC64LE ARCH additionally fails
```
TEST 52/53 [tests/999-uv_resident_set_memory.phpt]
========DIFF========
001- OK
001+ FAILED: {resident_mem} should be greater than 0 (maybe)
========DONE========
FAIL Check for uv_resident_set_memory [tests/999-uv_resident_set_memory.phpt] 
```

**Comment by andypost** [comment]
btw [building for PHP 8.4](https://gitlab.alpinelinux.org/alpine/aports/-/pipelines/259671) the original test is not fail anymore but ones from previous comment reproducible
