### ISSUE TITLE
IO issues

### ISSUE THREAD

**Issue by xtrime-ru** [bwoebi/php-uv#109]
Hello, im having issues with IO.

```php

\Revolt\EventLoop::repeat(1, function() {
    var_dump('Hello from main process');
    \Amp\File\touch('/app-host-link/test_file_main');
});

\Revolt\EventLoop::run();
```

Exception:
```text
string(23) "Hello from main process"

Fatal error: Uncaught Amp\File\FilesystemException: Could not touch file in /app-host-link/vendor/amphp/file/src/Driver/UvFilesystemDriver.php:548
Stack trace:
#0 [internal function]: Amp\File\Driver\UvFilesystemDriver::Amp\File\Driver\{closure}(-2)
#1 /app-host-link/vendor/revolt/event-loop/src/EventLoop/Driver/UvDriver.php(135): uv_run(Object(UVLoop), 2)
#2 /app-host-link/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(479): Revolt\EventLoop\Driver\UvDriver->dispatch(false)
#3 /app-host-link/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(541): Revolt\EventLoop\Internal\AbstractDriver->tick(false)
#4 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->Revolt\EventLoop\Internal\{closure}()
#5 /app-host-link/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(105): Fiber->start()
#6 /app-host-link/vendor/revolt/event-loop/src/EventLoop.php(406): Revolt\EventLoop\Internal\AbstractDriver->run()
#7 /app-host-link/test.php(35): Revolt\EventLoop::run()
#8 {main}

Next Revolt\EventLoop\UncaughtThrowable: Uncaught Amp\File\FilesystemException thrown in event loop callback {closure} defined in /app-host-link/test.php:30; use Revolt\EventLoop::setErrorHandler() to gracefully handle such exceptions: Could not touch file in /app-host-link/vendor/revolt/event-loop/src/EventLoop/UncaughtThrowable.php:13
Stack trace:
#0 /app-host-link/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(390): Revolt\EventLoop\UncaughtThrowable::throwingCallback(Object(Closure), Object(Amp\File\FilesystemException))
#1 /app-host-link/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(108): Revolt\EventLoop\Internal\AbstractDriver::Revolt\EventLoop\Internal\{closure}()
#2 /app-host-link/vendor/revolt/event-loop/src/EventLoop.php(406): Revolt\EventLoop\Internal\AbstractDriver->run()
#3 /app-host-link/test.php(35): Revolt\EventLoop::run()
#4 {main}
  thrown in /app-host-link/vendor/revolt/event-loop/src/EventLoop/UncaughtThrowable.php on line 13

exited with code 255
```

Regular `touch` works ok. 

Also i have issues with pcintl_fork. But i cant reproduce it with simple code.

**Comment by xtrime-ru** [comment]
https://github.com/amphp/file/commit/efeb737b1f19a7fcfe8a763c5ef2ad80dbac93dd
