### ISSUE TITLE
FAILED TEST: 330-poll-fd.phpt

### ISSUE THREAD

**Issue by steverhoades** [bwoebi/php-uv#4]
This test is resulting in a core dump against the latest PHP 7.0 nightly build.

**Comment by steverhoades** [comment]
System Tested:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04 LTS
Release:	14.04
Codename:	trusty

**Comment by steverhoades** [comment]
Reverted to RC6 and also an issue there.  Here is the stacktrace from gdb.
```
Program received signal SIGABRT, Aborted.
0x00007ffff6fc0cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6fc0cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6fc40d8 in __GI_abort () at abort.c:89
#2  0x00007ffff63cf2c0 in uv__io_poll (loop=loop@entry=0x7ffff6875000, timeout=-1) at src/unix/linux-core.c:182
#3  0x00007ffff63c2cff in uv_run (loop=0x7ffff6875000, mode=UV_RUN_DEFAULT) at src/unix/core.c:323
#4  0x00007ffff65ec511 in zif_uv_run (execute_data=0x7ffff6814170, return_value=0x7ffff6814150)
    at /home/vagrant/php-uv/php_uv.c:3278
#5  0x000000000088bf33 in ZEND_DO_ICALL_SPEC_HANDLER () at /home/vagrant/php/php-7.0.0RC6/Zend/zend_vm_execute.h:586
#6  0x000000000088b96e in execute_ex (ex=0x7ffff6814030) at /home/vagrant/php/php-7.0.0RC6/Zend/zend_vm_execute.h:414
#7  0x000000000088ba80 in zend_execute (op_array=0x7ffff687e000, return_value=0x0)
    at /home/vagrant/php/php-7.0.0RC6/Zend/zend_vm_execute.h:458
#8  0x00000000008312bb in zend_execute_scripts (type=8, retval=0x0, file_count=3)
    at /home/vagrant/php/php-7.0.0RC6/Zend/zend.c:1428
#9  0x000000000079eb06 in php_execute_script (primary_file=0x7fffffffd540) at /home/vagrant/php/php-7.0.0RC6/main/main.c:2471
#10 0x00000000008efae8 in do_cli (argc=4, argv=0x1082840) at /home/vagrant/php/php-7.0.0RC6/sapi/cli/php_cli.c:974
#11 0x00000000008f0cac in main (argc=4, argv=0x1082840) at /home/vagrant/php/php-7.0.0RC6/sapi/cli/php_cli.c:1345
```
