### ISSUE TITLE
Segmentation fault, uv_close

### ISSUE THREAD

**Issue by kivlara** [bwoebi/php-uv#8]
Hi,

Thank you for your help with compile. 
I compile and try my code and I get ```Segmentation fault```
here is the code:
```
$b = uv_pipe_init(uv_default_loop(), 0);
uv_pipe_connect($b, "/tmp/redis.sock", function($a, $stream)
{
        uv_close($stream); //Segmentation fault
});
uv_run();
```

**Comment by bwoebi** [comment]
The code works for me with existing and not-existing filepath and with non-socket file… So, what's the backtrace you get with the crash? (Run with gdb and use r and bt commands to run respectively generate the backtrace)

**Comment by kivlara** [comment]
```
Starting program: /root/.phpbrew/php/php-7.0.0/bin/php 1.php
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000724474be953d in php_uv_do_callback2 (retval_ptr=0x772531d22180, uv=0x724474beb3f1 <php_uv_close_cb>, params=0x772531d22170, param_count=1, type=PHP_UV_CLOSE_CB) at /tmp/php-uv/php_uv.c:1306
1306		if (ZEND_FCI_INITIALIZED(uv->callback[type]->fci)) {
(gdb) bt
#0  0x0000724474be953d in php_uv_do_callback2 (retval_ptr=0x772531d22180, uv=0x724474beb3f1 <php_uv_close_cb>, params=0x772531d22170, param_count=1, type=PHP_UV_CLOSE_CB) at /tmp/php-uv/php_uv.c:1306
#1  0x0000724474beb469 in php_uv_close_cb (handle=0x724474e6c018) at /tmp/php-uv/php_uv.c:2024
#2  0x00007244749b9bd2 in uv.finish_close () from /usr/local/lib/libuv.so.0.10
#3  0x00007244749b9c19 in uv.run_closing_handles () from /usr/local/lib/libuv.so.0.10
#4  0x00007244749b9ec7 in uv_run () from /usr/local/lib/libuv.so.0.10
#5  0x0000724474beccc9 in zif_uv_run (execute_data=0x724474e14100, return_value=0x724474e140f0) at /tmp/php-uv/php_uv.c:3281
#6  0x000000000082f802 in ZEND_DO_ICALL_SPEC_HANDLER () at /root/.phpbrew/build/php-7.0.0/Zend/zend_vm_execute.h:586
#7  0x000000000082f2bf in execute_ex (ex=0x724474e14030) at /root/.phpbrew/build/php-7.0.0/Zend/zend_vm_execute.h:414
#8  0x000000000082f3a0 in zend_execute (op_array=0x724474e7c000, return_value=0x0) at /root/.phpbrew/build/php-7.0.0/Zend/zend_vm_execute.h:458
#9  0x00000000007d871a in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /root/.phpbrew/build/php-7.0.0/Zend/zend.c:1428
#10 0x0000000000754544 in php_execute_script (primary_file=0x772531d25910) at /root/.phpbrew/build/php-7.0.0/main/main.c:2471
#11 0x00000000008908be in do_cli (argc=2, argv=0x4d269a0) at /root/.phpbrew/build/php-7.0.0/sapi/cli/php_cli.c:974
#12 0x000000000089174e in main (argc=2, argv=0x4d269a0) at /root/.phpbrew/build/php-7.0.0/sapi/cli/php_cli.c:1345
(gdb)
```
